remote_theme: rundocs/jekyll-rtd-theme
title: Quick Learning Symbol
description: Blockchain Symbol learning content
lang: it
baseurl: ""
url: "https://learn.it.symbol-community.com"
google:
  gtag: G-VBB48C2L7W
